#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;
use HTTP::Request::Common;

my $down_linkfile = $ARGV[ 0 ];
my $up_linkfile = $ARGV[ 1 ];
my $server = $ARGV[ 2 ];
my $client = $ARGV[ 3 ];
if ( not defined $down_linkfile or not defined $up_linkfile) {
  die "Usage: $0 DOWN_LINKFILE UP_LINKFILE\n";
}

my $receiver_pid = fork;

if ( $receiver_pid < 0 ) {
  die qq{$!};
} elsif ( $receiver_pid == 0 ) {
  # child
  exec q{$server} or die qq{$!};
}

chomp( my $prefix = qx{dirname `which mm-link`} );
my $tracedir = $prefix . q{/../share/mahimahi/traces};

# run the sender inside a linkshell and a delayshell
my @command = qw{mm-delay 20 mm-link UPLINK DOWNLINK};

# display livegraphs if we seem to be running under X
#if ( defined $ENV{ 'DISPLAY' } ) {
#  push @command, qw{--meter-uplink --meter-uplink-delay};
#}

push @command, qw{--once --uplink-log=/tmp/contest_uplink_log -- sh -c};

push @command, q{$client $MAHIMAHI_BASE 60001};

# for the contest, we will send data over Verizon's downlink
# (datagrump sender's uplink)
die unless $command[ 3 ] eq "UPLINK";
# when there's a loop going through each trace, the above line will look like the below:
print "Down linkfile: $down_linkfile\n";
$command[ 3 ] = qq{$tracedir/$down_linkfile};


print "Up linkfile: $up_linkfile\n";
die unless $command[ 4 ] eq "DOWNLINK";
$command[ 4 ] = qq{$tracedir/$up_linkfile};

system @command;

# kill the receiver
kill 'INT', $receiver_pid;

print "\n";

# analyze performance locally
system q{mm-throughput-graph 500 /tmp/contest_uplink_log > /dev/null}
  and die q{mm-throughput-graph exited with error. NOT uploading};

print "\n";
print qq{ done.\n\n};
print "\n";

